### ISSUE TITLE
Need decisions on non-implemented rules

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#2354]
The following rules are not implemented; probably we don't want to implement them at this stage, but I'd like to review this on a mangers call. 

Alex will tell us which rules P2GO implements: 
- [x] [gorule-0000004](https://github.com/geneontology/go-site/issues/932)		Reciprocal annotations for 'protein binding ; GO:0005515 : **OK, already in P2GO**
- [ ] gorule-0000009		Annotation Intersection Alerts: **Nice to have as a report (generated by P2GO)?** 
- [x] [gorule-0000023](https://github.com/geneontology/go-site/issues/741)		Materialize annotations for inter-branch links in the GO: **DONE P2GO** 
- [x] [gorule-0000024](https://github.com/geneontology/go-site/issues/2106)		Prevent propagation of certain terms by orthology **low priority** - covered by TC and do_not_annotate
- [ ] gorule-0000025		Creating more specific annotations by reasoning over extensions **low priority for a future project**
- [ ] gorule-0000036		Report annotations that involve gene products where the gene product is annotated to a term 'x' and 'regulation of X' (multiple annotations involved)  **Nice to have as a report (generated by P2GO)?** 
- [x] [gorule-0000038](https://github.com/geneontology/go-site/issues/1098)		Annotations using ISS/ISA/ISO evidence should refer to a gene product (in the 'with' column) where there exists  **DONE P2GO** 
- [x] [gorule-0000043](https://github.com/geneontology/go-site/issues/1177)		Check for valid combination of evidence code and GO_REF **DONE P2GO**  TBC
- [ ] gorule-0000045		With/from: Verify that the combination of evidence (ECO) codes conform to the rules in eco-usage-constraints.yaml  - as defined, redundant with gorule-0000045 - obsolete rule
- [ ] gorule-0000047		With/from: ChEBI IDs in With/from can only be used with terms that are descendants of GO:0005488 (binding) OR ChEBI IDs in With/from are not allowed for annotations to GO:0005515 protein binding & children or GO:0044877 protein-containing complex binding   **low priority**
- [x] [gorule-0000049](https://github.com/geneontology/go-site/issues/916)		If the annotation has 'contributes_to' as its qualifier, verify that at least one annotation to GO:0043234 (protein complex), or one of its child terms exists **DONE P2GO**  
- [ ] [gorule-0000051](https://github.com/geneontology/go-site/issues/2058)	Warning	Direct annotations to GO:0005488 binding require a value in the Annotation Extension field  **low priority**
- [x] [gorule-0000053](https://github.com/geneontology/go-site/issues/2109)		NOT annotation should not have extension **DONE P2GO**  
- [ ] gorule-0000054		Genes annotated with ND should have no other annotations for that aspect **DONE P2GO** (noting that 'binding' annotations should probably not count). It would be nice to generate a report of genes annotated to ND + binding
- In P2GO, if there is an EXP, one cannot add an ND. But if there is an ND, one CAN add an EXP
- [ ] gorule-0000056		Annotations should validate against GO shape expressions: for GO-CAM & could be used for extensions  **Nice to have as a report**
- [x] [gorule-0000058](https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000058.md)	Filter	Object extensions should conform to the extensions-patterns.yaml file in metadata: **This is done during IMPORTS only** 

@mugitty @kltm @vanaukenk

**Comment by pgaudet** [comment]
Replace by new tasks here https://github.com/geneontology/go-site/issues/2435
